// <auto-generated />
namespace eLearningLMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DetailFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DetailFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201906040803476_DetailFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
